### ISSUE TITLE
Issue with material properties in SW4

### ISSUE THREAD

**Issue by shaharkadmiel** [geodynamics/sw4#1]
I am trying to prescribe a custom gradient to material properties as the builtin gradient option in `SW4` does not apply to Qp and Qs and also because I am interested in a slightly more complex gradient than a simple linear one. When checking the material properties stored in the images written by `SW4` I noticed that the values are off by quite a bit.

I have created a sample input file which produces the issue that can be downloaded [here](https://www.dropbox.com/s/eoao8l6wdxtmfyg/material_test.sw4?dl=1).

I don't really understand where the issue originates. It might be just wrong data in the `SW4` image file(I hope that is the case) because SW4 reports the correct values in stdout (full stdout [here](https://www.dropbox.com/s/0mycmrfi66tr2p4/stdout.txt?dl=1)):

```
       ----------- Material properties ranges ---------------
       1.61000000e+03 kg/m^3 <=  Density <= 1.99000000e+03 kg/m^3
       6.50000000e+02 m/s    <=  Vp      <= 9.64000000e+02 m/s
       3.50000000e+02 m/s    <=  Vs      <= 6.66000000e+02 m/s
       1.44736842e+00        <=  Vp/Vs   <= 1.85714286e+00
       1.97225000e+08 Pa     <=  mu      <= 8.82676440e+08 Pa
       5.95263090e+07 Pa     <=  lambda  <= 2.85775000e+08 Pa
       Using attenuation 
       2.00000000e+00        <=  Qs      <= 5.20000000e+01  
       3.00000000e+00        <=  Qp      <= 1.03000000e+02  
       ------------------------------------------------------
```

Below is a workflow to demonstrate the issue: (viewable as a static notebook [here](http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/gakmdsneom6kesu/SW4_MaterialModel_Issue.ipynb))

- First I parse the [input file](https://www.dropbox.com/s/eoao8l6wdxtmfyg/material_test.sw4?dl=1) and plot the desired material properties as they are specified in the block commands.
- I then read the Vp, Vs, and rho, cross section images created by `SW4` and plot the images
- I then plot a sample column from the center of each image array to present the resulting material properties.
- Finally I compare the desired and resulting properties side by side and report the `min`, `max`, values.

I guess I would like to know if this issue is reproducible on other machines and if so if it is a real issue? That is: Does the `SW4` computation actually runs with wrong material properties or does it simply report the wrong values in the image files.

**Comment by andersp** [comment]
Hi Shahar,
SW4 uses the Lame' parameters (lambda,mu) as well as the density to describe an isotropic material. When you turn on visco-elastic modeling it also uses the parameters (lambda_q, mu_q) for each mechanism q=1,2,…,nmech. To get the correct phase velocities at the specified frequency (phasefreq), you need to rescale the elastic parameters (lambda, mu). However, when SW4 outputs images with cp and cs-velocities, it always uses the formulas cp=sqrt((2*mu+lambda)/rho) and cs=sqrt(mu/rho). So those are the values you observe in the image files. Note that the density is not changed by this procedure and is correctly recorded in the image file. For normal values of Qp and Qs, the recorded values of cp and cs values are not far from the specified ones, but when Qp and Qs gets very small you can get a significant deviation. This a consequence of the dispersive nature of visco-elastic materials. One way of interpreting the (cp, cs) values in the image files is the phase velocities in the limit of zero frequency.
Another comment about your input file is that the material jumps coincide with grid points, so you evaluate all properties right in the jumps. It would be better to offset the jumps in the material a little in z to avoid any effects of round-off.
/Anders

**Comment by shaharkadmiel** [comment]
Thanks for the detailed answer Anders
