### ISSUE TITLE
Replace "evalMax" with "elevMax" in EW::extractTopographyFromCartesianFile()

### ISSUE THREAD

**Issue by wmheigl** [geodynamics/sw4#106]
The method extractTopographyFromCartesianFile(string) in the class EW reports elevMax as 'evalMax' on line 5139.
`if (proc_zero())
     printf("xMin=%e, xMax=%e..., **evalMax**=%e\n",...);`

**Comment by andersp** [comment]
The name has been corrected in the developer branch.
