### ISSUE TITLE
fileio not optional

### ISSUE THREAD

**Issue by houjun** [geodynamics/sw4#111]
From @andersp

> The fileio command should be optional. Right now the code crashes with a segfault without a fileio command in the input file. This needs to get fixed.

**Comment by houjun** [comment]
@bjorn2 Anders and I found that mPath variable initialization in EW.C is commented out in [this merge](https://github.com/geodynamics/sw4/commit/15ba75c7082e3aa0a6108ea331720e79eef63c21#diff-715ffca0821194d5b64ca56040ffd8065e70df39859f116ff08c0b5707f5bbaaL360), and thus causing the requirement in the fileio command processing to initialize it. And if there is no fileio command, SW4 will crash. Any idea how we can fix that?

**Comment by bjorn2** [comment]
I have fixed this bug now.
