### ISSUE TITLE
error message from proj

### ISSUE THREAD

**Issue by bjorn2** [geodynamics/sw4#112]
Sometimes the message is printed when running sw4:

proj_create_operation_factory_context: Cannot find proj.db
pj_obj_create: Cannot find proj.db

Does anyone know what is causing this ? Is it harmful ? SW4 still runs ok.

**Comment by houjun** [comment]
@bjorn2 , what version of proj are you using? If you are using 7 or 8, check whether the install directory has proj-install/share/proj/proj.db file.
