### ISSUE TITLE
Finest horizontal grid spacing in sfile?

### ISSUE THREAD

**Issue by jf-huang** [geodynamics/sw4#115]
The “Coarsest horizontal grid spacing” attribute in the sw4-generated sfile seems to refer to the finest horizontal grid spacing (ie. grid_0 instead of grid_n), for example, as also shown in the h5dump example in section 12.6 of the SW4-UserGuide.pdf. Is this expected?

**Comment by houjun** [comment]
You are right, it should be finest instead of coarsest, will change the name of the attribute to "Finest horizontal grid spacing”.

**Comment by jf-huang** [comment]
Got it, thanks!
