### ISSUE TITLE
Supergrid

### ISSUE THREAD

**Issue by Navids94** [geodynamics/sw4#138]
Hello,
Would you please let me know whether the threshold of 30 grid points for applying super grid is based on coarsest h (grid size at the bottom) or based on top layer grid size? I have considered four refinements, with h=347m for the bottom layer and h=21m for the top layer (basin)
Thanks a lot

**Comment by andersp** [comment]
It has constant physical thickness in all grids. And it needs to be at least 30 grid points in any grid, which means that the physical thickness is determined by the coarsest grid.

**Comment by Navids94** [comment]
Thank you so much for answering the question.
Therefore, I have constant boundary conditions width(30gp*h(347)=10410) from the top to the bottom of the computational domain because I have determined the location of receivers, sources, and edges of the basin based on the number of grid points from the started point (bottom left ). As a result, it is correct to consider the coarsest grid(h=347) for determining the location of either receivers or sources.
I appreciate it
