### ISSUE TITLE
Missing DELTA and ORIGINTIME attributes in rechdf5 output

### ISSUE THREAD

**Issue by jf-huang** [geodynamics/sw4#154]
In the SW4 Users Guide, it is noted there are 4 global attributes in the root group of the result file: DATETIME, UNIT, DELTA and ORIGINTIME. However, the DELTA and ORIGINTIME attributes seems to be missing, as show below:
![image](https://user-images.githubusercontent.com/44045796/209242503-48162b94-6f97-433d-884e-f1f809a3e3f3.png)
Could this be fixed? Thanks.

**Comment by houjun** [comment]
@jf-huang "DELTA" and "ORIGINTIME" are stored as HDF5 **datasets** instead of **attributes**,  e.g. h5file['DELTA']

**Comment by jf-huang** [comment]
Thanks @houjun ! Yes, they are there, sorry did not recognize them as they were immersed in all the other recorded stations... Closing now.
