### ISSUE TITLE
Instability issue after long time

### ISSUE THREAD

**Issue by jf-huang** [geodynamics/sw4#167]
Hi, I created a 5km(x)×3km(y)×6km(z) domain in SW4 with a 1D layered velocity model and a point source located at depth. The base grid spacing is 16m with a mesh refinement at 408m; the number of grid points in the supergrid is set to 30 (default).  The solution looks fine during the first 9s, after which the domain should be essentially silent. However, the motions in the top grid grow to very large values very rapidly and propagate to the bottom grid, as shown in the following movie (star is the hypocenter; the dashed white line delineates the boundary between the half-space below and the overlying layers):
![output](https://user-images.githubusercontent.com/44045796/223785084-b526c89a-c1ff-4d30-a25f-95f999d82828.gif)
This instability issue also happens in another larger domain with mesh refinements. Do you know where this issue come from and how I can resolve it? 

Many thanks.

**Comment by jf-huang** [comment]
Hi Dr. Petersson @andersp, thanks for looking into this. Attached please find the sw4input file and pfile that I used. I am using a recent SW4 version in the developer branch (after this PR #137). The Poisson's ratio is 0.32 (Vp/Vs=1.9) throughout the whole domain. Let me know if you need anything else. 
[testModel.zip](https://github.com/geodynamics/sw4/files/10923795/testModel.zip)

**Comment by andersp** [comment]
Thanks @jf-huang . Can you also provide the output that sw4 generates when you run this case?

**Comment by jf-huang** [comment]
Sure @andersp , the output file is attached (output for the time step phase is truncated).
[sw4out.txt](https://github.com/geodynamics/sw4/files/10924162/sw4out.txt)

**Comment by andersp** [comment]
When defining a background material, you should not specify z1=0.0. The reason is that there are ghost points just above the free surface with z-coordinate less than 0.
I ran your case after removing the z1=0 keyword in the block command, i.e.,

block vp=3600.0 vs=1900.0  rho=2178.0 qp=200.0 qs=100.0

Now sw4 remains stable. Here are the ux, uy and uz images
![ux](https://user-images.githubusercontent.com/8921735/224507915-1fcc1e1c-4001-40cb-b981-98ecb423c2a5.png)
![uy](https://user-images.githubusercontent.com/8921735/224507927-47e8c2b7-2deb-4d64-a5e4-d3d6e039ab45.png)
![uz](https://user-images.githubusercontent.com/8921735/224507935-cda34a07-04cc-4dd2-881d-3afa1931ef53.png)

**Comment by jf-huang** [comment]
Hi Dr. Petersson @andersp, thanks for the check! I have observed similar instability in one of our generic model consisting of a 1D layered crust (created with the block command; similar to the example above, the top block is specified with z1=0.0), and a wedge basin on the right side. Snapshots (local surface region) of the vecocity magnitude (ux & uy & uz) are shown below:
![image](https://user-images.githubusercontent.com/44045796/224510870-17cd80e7-e9b4-4851-8904-f80e7d81b6f6.png)
At t=16.2s, the fault rupture process is essentially finished, while snapshots at t=24.3s and t=40.5s show the buildup of the large motions. Different than the previous model where the instability first happened at the surface, the instability in this model happened at the second mesh refinement below the free surface and the large motions were mostly confined to the rock side (left). Unfortunately, I am not able to rerun this model in the coming days. Do you think this phenomenon is also caused by the fact that  z1=0.0 is specified in the top block? Since the input files are relatively large, I can email them to you if necessary. Thanks again for the help.

**Comment by andersp** [comment]
I suggest you rerun your case after removing the z1=0 keyword from the background material model. I don't have the time to rerun your case.

**Comment by jf-huang** [comment]
Thanks for the suggestion @andersp , I will report back here when I have new results.

**Comment by jf-huang** [comment]
Hi Dr. Petersson @andersp, just wanted to report back that the issue is resolved by setting cfl to 1.0. Thanks for the input! Closing now.
