### ISSUE TITLE
HELP! About the source order with a discrete-time function file

### ISSUE THREAD

**Issue by BFF-LEI-Lei** [geodynamics/sw4#170]
Hi,
When I define a source by a discrete-time function file, the code always outputs the warning information like the below:

# not foundt error: Source Error: Source time function file x1_x_001.txt

I wonder how to deal with it.

Here are my in-file, out-file, and discrete-time function files, from which you can see more details about my issue.

Thanks a lot!

[SW4-ORDER.in.txt](https://github.com/geodynamics/sw4/files/10942518/SW4-ORDER.in.txt)
[SW4-ORDER.out.txt](https://github.com/geodynamics/sw4/files/10942524/SW4-ORDER.out.txt)
[x1_x_001.txt](https://github.com/geodynamics/sw4/files/10942521/x1_x_001.txt)
[x1_x_002.txt](https://github.com/geodynamics/sw4/files/10942522/x1_x_002.txt)
[x1_x_003.txt](https://github.com/geodynamics/sw4/files/10942523/x1_x_003.txt)

**Comment by andersp** [comment]
Looks like you are running an old version of sw4. You should first  update your installation to version 3 of sw4. 
The reason you are getting this error is that sw4 can't find the file with the time function. Are these files in the same directory as you start sw4 from?

**Comment by BFF-LEI-Lei** [comment]
Thanks for your reply!
Yes, I surely put all my discrete-time function files and the SW4-ORDER.in file in the same folder.
Perhaps you can try to run my code to further find where the mistake is.
As for the installation, can I have version 3 of sw4 on ubuntu 18?  I'm afraid the old libs on ubuntu 18 don't support the new ability of the latest version of sw4.

Thank you again for your reply！
Best wishes！

**Comment by andersp** [comment]
Your case runs without problem on my machine. But I had to first get rid of the DOS end of line characters in all your files, which makes me suspect that the input files were created on a Windows machine? The easiest way of getting rid of these characters is with the dos2unix app.

**Comment by BFF-LEI-Lei** [comment]
Thank you very much for your great suggestion! It helps me solve my problem!
