### ISSUE TITLE
Non-zero values of velocity at source coordinate for substantial amount of time

### ISSUE THREAD

**Issue by avinash07guddu** [geodynamics/sw4#2]
[Summary.pdf](https://github.com/geodynamics/sw4/files/213594/Summary.pdf)

Hi Everyone,

I am having an issue with SW4 where I get non-zero values in velocity
at source position for a substantial amount of time (after source time
function becomes very small) and I am not sure what exactly I am doing
wrong.

In the attached file (Summary.pdf), Figure 1 shows a screenshot of
velocity in YZ plane at x=1.393 km (passing through the source at
x=1.393, y=1.925 and z=0.469 km) at t=7.5 seconds. Color is supposed
to be scaled as red to blue from negative(peak absolute amplitude) to
positive(peak absolute amplitude) with white for zero. As you can see
the highest amplitude is a dot at the source position (y=1.925 km,
z=0.46 km). If I replace values at 7x7 grid points around the source
with zeros, then I can see the wavefield slightly better and the peak
amplitude decreases from 1.1e-5 m/s to 2.7e-6 m/s (Figure 2).

In figure 3 and 4, I am plotting the velocity and displacement values
at the 7x7 grid points around the source, and you can see non-zero
very slowly decreasing values of velocity that persist even at 15-20
seconds. When I integrate them, I can see a slight increase of
displacements with time but I am not sure if they reach steady state
value (Figure 4).

My grid spacing is 7 m for minimum shear wave velocity 150 m/s. I use
a Gaussian source time function with freq 3.1416 (so, f0=0.5 Hz,
fmax=f0 x 2.5 = 1.25 Hz, and 150/1.25/7 = 17 grid points per
wavelength for fmax). My t0 is 2.0 seconds( which is greater than
6/freq=1.91 s) so satisfies g(t=t0)=3.4e-9 which is less than 1e-8.
The source time function goes below 1e-15 after 5 seconds.
The source is a moment tensor source  very close to a strong material
discontinuity. I use supergrid size 73.

I will be very grateful if someone can point out what I have done
wrong. Due to computation limitations, I cannot really go to lower
grid spacing. I am currently trying another run at higher value of t0
(2.5 s).

I have also attached my input file, output log, and output source-time function file g1.txt.

[input_te1_gau.txt](https://github.com/geodynamics/sw4/files/213596/input_te1_gau.txt)
[slurm-2609.txt](https://github.com/geodynamics/sw4/files/213598/slurm-2609.txt)
[g1.txt](https://github.com/geodynamics/sw4/files/213600/g1.txt)

Thanks.
Regards,
Avinash

**Comment by andersp** [comment]
Hi Avinash,
Please post your input file and P-file material model. If the files are large, you can post a link to, e.g., drop box.
/Anders

**Comment by avinash07guddu** [comment]
Thanks. My input file is at the end of the my previous post.
Here is the link to the model p-file

https://drive.google.com/file/d/0BwSFMX7j0vyZTk0xNkRhRHozTjA/view?ts=570beda8
