### ISSUE TITLE
Spack Build error - missing H5ZROOT

### ISSUE THREAD

**Issue by pjmaechling** [geodynamics/sw4#222]
Spack build exits without finishingwith this error. Any suggestions?

[+] /home1/maechlin/test_sw4/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/py-h5py-3.11.0-v7edyk7wzrzczn6yuylwktz4kwgt72ay
==> Installing sw4-3.0-tzi3wmggrk7taubhrjleomy4ifekz4ow [67/67]
==> No binary for sw4-3.0-tzi3wmggrk7taubhrjleomy4ifekz4ow found: installing from source
==> No patches needed for sw4
==> sw4: Executing phase: 'edit'
==> Error: KeyError: 'No spec with name h5z-zfp in sw4@=3.0%gcc@=8.3.0+fftw+hdf5+openmp+proj~zfp build_system=makefile arch=linux-centos7-skylake_avx512 ^[deptypes=build] autoconf@=2.72%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build] automake@=1.16.5%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] berkeley-db@=18.1.40%gcc@=8.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-centos7-skylake_avx512 ^[deptypes=build] bison@=3.8.2%gcc@=8.3.0~color build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link,run] bzip2@=1.0.8%gcc@=8.3.0~debug~pic+shared build_system=generic arch=linux-centos7-skylake_avx512 ^[deptypes=build] ca-certificates-mozilla@=2023-05-30%gcc@=8.3.0 build_system=generic arch=linux-centos7-skylake_avx512 ^[deptypes=build] cmake@=3.29.6%gcc@=8.3.0~doc+ncurses+ownlibs build_system=generic build_type=Release patches=dbc3892 arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] curl@=8.7.1%gcc@=8.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-centos7-skylake_avx512 ^[deptypes=build] diffutils@=3.10%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] expat@=2.6.2%gcc@=8.3.0+libbsd build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] fftw@=3.3.10%gcc@=8.3.0+mpi~openmp~pfft_patches+shared build_system=autotools precision=double,float arch=linux-centos7-skylake_avx512 ^[deptypes=build,run] findutils@=4.9.0%gcc@=8.3.0 build_system=autotools patches=440b954 arch=linux-centos7-skylake_avx512 ^[deptypes=link] gcc-runtime@=8.3.0%gcc@=8.3.0 build_system=generic arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] gdbm@=1.23%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] gettext@=0.22.5%gcc@=8.3.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=link virtuals=libc] glibc@=2.17%gcc@=8.3.0 build_system=autotools patches=be65fec,e179c43 arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] gmake@=4.4.1%gcc@=8.3.0~guile build_system=generic arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] hdf5@=1.14.3%gcc@=8.3.0~cxx~fortran+hl~ipo~java~map+mpi+shared~subfiling~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make patches=82088c8 arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] hwloc@=2.9.3%gcc@=8.3.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] krb5@=1.21.2%gcc@=8.3.0+shared build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] libbsd@=0.12.2%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] libedit@=3.1-20230828%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] libevent@=2.1.12%gcc@=8.3.0+openssl build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] libffi@=3.4.6%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link virtuals=iconv] libiconv@=1.17%gcc@=8.3.0 build_system=autotools libs=shared,static arch=linux-centos7-skylake_avx512 ^[deptypes=build,link virtuals=jpeg] libjpeg-turbo@=3.0.3%gcc@=8.3.0~ipo~jpeg8~partial_decoder+pic build_system=cmake build_type=Release generator=make libs=shared,static arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] libmd@=1.0.4%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] libpciaccess@=0.17%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] libsigsegv@=2.14%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] libtiff@=4.6.0%gcc@=8.3.0+ccitt~ipo~jbig+jpeg~jpeg12~lerc~libdeflate+logluv~lzma+lzw+next~old-jpeg+packbits~pic~pixarlog+shared+thunder~webp+zlib~zstd build_system=cmake build_type=Release generator=make arch=linux-centos7-skylake_avx512 ^[deptypes=build] libtool@=2.4.7%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] libxcrypt@=4.4.35%gcc@=8.3.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] libxml2@=2.10.3%gcc@=8.3.0+pic~python+shared build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,run] m4@=1.4.19%gcc@=8.3.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-centos7-skylake_avx512 ^[deptypes=build] nasm@=2.15.05%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] ncurses@=6.5%gcc@=8.3.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] nghttp2@=1.62.0%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] numactl@=2.0.14%gcc@=8.3.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-centos7-skylake_avx512 ^[deptypes=build,link virtuals=blas,lapack] openblas@=0.3.27%gcc@=8.3.0~bignuma~consistent_fpcsr+dynamic_dispatch+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=none arch=linux-centos7-skylake_avx512 ^[deptypes=build,link virtuals=mpi] openmpi@=5.0.3%gcc@=8.3.0~atomics~cuda~gpfs~internal-hwloc~internal-libevent~internal-pmix~java~legacylaunchers~lustre~memchecker~openshmem~orterunprefix~romio+rsh~static+vt+wrapper-rpath build_system=autotools fabrics=none romio-filesystem=none schedulers=none arch=linux-centos7-skylake_avx512 ^[deptypes=run] openssh@=9.7p1%gcc@=8.3.0+gssapi build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] openssl@=3.3.1%gcc@=8.3.0~docs+shared build_system=generic certs=mozilla arch=linux-centos7-skylake_avx512 ^[deptypes=build,run] perl@=5.38.2%gcc@=8.3.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-centos7-skylake_avx512 ^[deptypes=run] pigz@=2.8%gcc@=8.3.0 build_system=makefile arch=linux-centos7-skylake_avx512 ^[deptypes=build,run virtuals=pkgconfig] pkgconf@=2.2.0%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] pmix@=5.0.2%gcc@=8.3.0~docs+pmi_backwards_compatibility~python~restful build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] proj@=9.4.1%gcc@=8.3.0+curl~ipo~pic+shared+tiff build_system=cmake build_type=Release generator=make arch=linux-centos7-skylake_avx512 ^[deptypes=build] py-cython@=0.29.36%gcc@=8.3.0 build_system=python_pip patches=c4369ad arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] py-h5py@=3.11.0%gcc@=8.3.0+mpi build_system=python_pip arch=linux-centos7-skylake_avx512 ^[deptypes=build,run] py-mpi4py@=3.1.6%gcc@=8.3.0 build_system=python_pip arch=linux-centos7-skylake_avx512 ^[deptypes=build,run] py-numpy@=1.25.2%gcc@=8.3.0 build_system=python_pip patches=873745d arch=linux-centos7-skylake_avx512 ^[deptypes=build] py-pip@=23.1.2%gcc@=8.3.0 build_system=generic arch=linux-centos7-skylake_avx512 ^[deptypes=build] py-pkgconfig@=1.5.5%gcc@=8.3.0 build_system=python_pip arch=linux-centos7-skylake_avx512 ^[deptypes=build] py-poetry-core@=1.8.1%gcc@=8.3.0 build_system=python_pip arch=linux-centos7-skylake_avx512 ^[deptypes=build,run] py-setuptools@=63.4.3%gcc@=8.3.0 build_system=generic arch=linux-centos7-skylake_avx512 ^[deptypes=build] py-wheel@=0.41.2%gcc@=8.3.0 build_system=generic arch=linux-centos7-skylake_avx512 ^[deptypes=build,link,run] python@=3.11.9%gcc@=8.3.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-centos7-skylake_avx512 ^[deptypes=build,run] python-venv@=1.0%gcc@=8.3.0 build_system=generic arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] readline@=8.2%gcc@=8.3.0 build_system=autotools patches=bbf97f1 arch=linux-centos7-skylake_avx512 ^[deptypes=build,link] sqlite@=3.43.2%gcc@=8.3.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=run] tar@=1.34%gcc@=8.3.0 build_system=autotools zip=pigz arch=linux-centos7-skylake_avx512 ^[deptypes=build,link virtuals=uuid] util-linux-uuid@=2.40.2%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build] util-macros@=1.20.1%gcc@=8.3.0 build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=build,link,run] xz@=5.4.6%gcc@=8.3.0~pic build_system=autotools libs=shared,static arch=linux-centos7-skylake_avx512 ^[deptypes=build,link virtuals=zlib-api] zlib-ng@=2.2.1%gcc@=8.3.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-centos7-skylake_avx512 ^[deptypes=run] zstd@=1.5.6%gcc@=8.3.0+programs build_system=makefile compression=none libs=shared,static arch=linux-centos7-skylake_avx512'

/home1/maechlin/test_sw4/spack/var/spack/repos/builtin/packages/sw4/package.py:51, in edit:
         48        os.environ["fftw"] = "yes"
         49        os.environ["SW4ROOT"] = spec["proj"].prefix
         50        os.environ["HDF5ROOT"] = spec["hdf5"].prefix
  >>     51        os.environ["H5ZROOT"] = spec["h5z-zfp"].prefix
         52        os.environ["ZFPROOT"] = spec["zfp"].prefix
         53        os.environ["FFTWHOME"] = spec["fftw"].prefix
         54        os.environ["EXTRA_LINK_FLAGS"] = "-lstdc++ -lm -ldl "

**Comment by aicesun** [comment]
try `spack install sw4 ^h5z-zfp`

**Comment by pjmaechling** [comment]
Yes, that solved my spack build issue. I was able to generate an executable. Thank you for your quick response.
