### ISSUE TITLE
Comparison between empirical formula and SW4 simulation results

### ISSUE THREAD

**Issue by Zzzzsxb** [geodynamics/sw4#225]
Under poor computing conditions, I divided the computational grid into 1000m and resolved the seismic wave frequency to 0.05hz, but the calculated PGA is much higher than the result obtained by GMMS. What is the reason? It stands to reason that low-frequency seismic waves will not produce such a large result.

**Comment by andersp** [comment]
What is the source time function? When choosing the source frequency, did you follow the instructions in section 4.4 of the user's guide?

**Comment by Zzzzsxb** [comment]
I used the SRF file generated by Song's Rupture Model Generator

**Comment by andersp** [comment]
Whenever using sources from a SRF file you must use the prefilter command to limit the frequency content.

**Comment by Zzzzsxb** [comment]
Thank you very much, this helps me a lot
