### ISSUE TITLE
Building SW4 with Proj.4

### ISSUE THREAD

**Issue by shaharkadmiel** [geodynamics/sw4#3]
Hi,

I am trying to build SW4 with the Proj.4 libs on a new cluster. It builds however when I execute `sw4` I get:

```
$ sw4 -v
sw4: error while loading shared libraries: libproj.so.9: \
     cannot open shared object file: No such file or directory
```

Which is weird because:

```
$ locate libproj
/share/apps/lib/libproj.a
/share/apps/lib/libproj.la
/share/apps/lib/libproj.so
/share/apps/lib/libproj.so.9
/share/apps/lib/libproj.so.9.1.0
```

`make` completes with no errors.

Here is the end of the make output:

```
*** Configuration file: ' configs/make.inc ' ***
********* User configuration variables **************
debug= no  proj= yes  etree= no  SW4ROOT= /share/apps
CXX= mpicxx EXTRA_CXX_FLAGS=
FC= mpif77  EXTRA_FORT_FLAGS=
EXTRA_LINK_FLAGS= -L/usr/lib64 -llapack -lblas -lgfortran
******************************************************
cd optimize; mpicxx -O -I../src -DENABLE_PROJ4 -I/share/apps/include \
-o sw4 main.o EW.o Sarray.o version.o parseInputFile.o \
ForcingTwilight.o curvilinearGrid.o boundaryOp.o bcfort.o \
twilightfort.o rhs4th3fort.o parallelStuff.o Source.o \
MaterialProperty.o MaterialData.o material.o setupRun.o solve.o \
solerr3.o Parallel_IO.o Image.o GridPointSource.o MaterialBlock.o \
testsrc.o TimeSeries.o sacsubc.o SuperGrid.o addsgd.o velsum.o \
rayleighfort.o energy4.o TestRayleighWave.o MaterialPfile.o \
Filter.o Polynomial.o SecondOrderSection.o time_functions.o Qspline.o \
lamb_exact_numquad.o twilightsgfort.o EtreeFile.o MaterialIfile.o \
GeographicProjection.o rhs4curvilinear.o curvilinear4.o \
rhs4curvilinearsg.o curvilinear4sg.o gradients.o Image3D.o \
MaterialVolimagefile.o MaterialRfile.o randomfield3d.o \
innerloop-ani-sgstr-vc.o bcfortanisg.o AnisotropicMaterialBlock.o \
checkanisomtrl.o computedtaniso.o dqags.o dqagse.o  dqaws.o  dqawse.o \
dqc25s.o dqcheb.o  dqelg.o  dqk15w.o  dqk21.o  dqmomo.o dqpsrt.o \
dqwgts.o  qaws.o  qawse.o  qc25s.o qcheb.o  qk15w.o  qmomo.o  qpsrt.o \
qwgts.o xerror.o d1mach.o r1mach.o -L/share/apps/lib -lproj \
-L/usr/lib64 -llapack -lblas -lgfortran
    
``'-.,_,.-'``'-.,_,.='``'-.,_,.-'``'-.,_,.='````'-.,_,.-'``'-.,_,.='``


  _________    ____      __      ____    _    __
 /   ____  \   \   \    /  \    /   /   / |  |  |  
 |  |    \./    \   \  /    \  /   /   /  |  |  |
 |  |______      \   \/      \/   /   /   '--'  |
 \______   \      \              /    |______   |
        |  |       \     /\     /            |  |      
 /`\____|  |        \   /  \   /             |  |      
 \_________/         \_/    \_/              |__|      
                                       
   __       __  ____    ____  _______    ______    __  
  |  |     |  | \   \  /   / |   ____|  /    __|  |  | 
  |  |     |  |  \   \/   /  |  |__     |   (__   |  | 
  |  |     |  |   \      /   |   __|    \__    |  |  | 
  |  `----.|  |    \    /    |  |____    __)   |  |__| 
  |_______||__|     \__/     |_______|  (_____/   (__)
     

``'-.,_,.-'``'-.,_,.='``'-.,_,.-'``'-.,_,.='````'-.,_,.-'``'-.,_,.='``
*** Build directory:  optimize  ***
```

Any suggestions?

**Comment by shaharkadmiel** [comment]
I solved the problem and here is what I did for future reference:

I use [Rocks Clusters](http://www.rocksclusters.org/wordpress/) because it is really fast and easy to setup and then maintain clusters. There are some caveats however and this is apparently one of them.

Compiling software from source is done in `/share/apps`  so that all nodes have access to the compiled code. Up till now, it was enough to have the `/share/appa/bin` path added to the `PATH` environmental variable. Now the `/share/apps/lib` path needed to be added to the `LD_LIBRARY_PATH` env variable.

There are several ways to do this:

I suppose one way is to have all users add the line

```bash
export LD_LIBRARY_PATH=/share/apps/lib:$LD_LIBRARY_PATH
```

to their `~/.bashrc`, which *might (I haven't checked...)* work but really depends on the users...

**This is what I did:**
Turns out there is a special place for this: `/etc/ld.so.conf`. This is where the system keeps track of the paths to the libraries required for linking during compilation. Before I edited the file, it looked like this:

```bash
$ cat /etc/ld.so.conf
include ld.so.conf.d/*.conf
/lib64
/usr/lib64
/usr/kerberos/lib64
```

As root, `$ echo /share/apps/lib >> /etc/ld.so.conf` did the trick on the frontend (or the current login node) but needed to propagate to the rest of the cluster.

`$ ldconfig ; rocks sync config` does that but only temporary. If a node gets reinstalled from the kickstart file (after a power failure or a major update for instance...) this is lost.

Post installation stuff is handled by the `/export/rocks/install/site-profiles/6.1/nodes/extend-base.xml` file. Adding

```xml
<!-- Edit the /etc/ld.so.conf file for the entire cluster -->
<file name="/etc/ld.so.conf" mode="append">
/share/apps/lib
</file>
```

to the `<post> ... </post>` section takes care of that.

Computations are up and crunching again...

Thanks

**Comment by andersp** [comment]
Hi Shahar,
Building any code with shared libraries can be a bit tricky. The fundamental problem is that the –L flag only tells the linker where to find the shared libraries for an executable. Under unix, this information is not saved together with the executable program (sw4 in this case). So if your shared library is in a non-standard location, you either have to modify the LD_LIBRARY_PATH variable, or add extra flags to the link line. Unfortunately, the syntax for those extra linker flags is not standardized and depends on the type of linker (intel, gcc, pgi, etc).

However, once sw4 is built, you can always check if it knows where to find all shared libraries by running the unix command 'ldd sw4'. On Mac OSX it is called 'otool –L sw4'.

Here is a nice article that goes over the issues in more detail: https://gcc.gnu.org/ml/gcc-help/2005-12/msg00017.html
Good luck!
Anders

**Comment by shaharkadmiel** [comment]
Thanks @andersp for the detailed explanation.

The solution I implemented, although system specific is robust in my opinion as it accounts for future code building with third party shared objects. However, if I understand you correctly, and after reading the article you referred me to, adding the following lines to `config/make.inc` would have done it.

```shell
SW4ROOT = /share/apps
EXTRA_LINK_FLAGS = -L/usr/lib64 -llapack -lblas -lgfortran \
                   -L$(SW4ROOT)/lib -lproj -Wl,-rpath=$(SW4ROOT)/lib
```

**Comment by andersp** [comment]
That linker flag works on our systems in Livermore, but it is not universal.
