### ISSUE TITLE
Restart issue: time series files don't match on restart

### ISSUE THREAD

**Issue by drhansj** [geodynamics/sw4#33]
Using 81660fd, running a version of examples/meshrefine/loh1-slow-mr-order4.in but with restart.

One test that works fine (usgs ascii, sac binary) on restart is here:
performance/scec/LOH.1-h400-check.in

I tried a bunch of other tests beyond Artie's mini Hayward, including ones with mesh refinement, attenuation (3 mech, 1 mech).

One I tried with and w/o MR is this one:
- examples/meshrefine/loh1-slow-mr-order4.in

If I comment out the refinement line, then everything is correct on restart and matches the baseline.

**Comment by drhansj** [comment]
@andersp and @bjorn2 would appreciate any ideas you have to investigate this.

Can you think of a place in the code where MR might require extra initialization (ghost cells, materials, etc.) after reading in from a restart file?

**Comment by drhansj** [comment]
@andersp : I found a second example, loh3 with mr and att (3 mech). When I comment out the mr and att, I get matching time series data. So extra initialization with attenuation is probably an issue, too.

**Comment by andersp** [comment]
One routine that needs to be called for MR to work properly is setup_MR_coefficients(). It is called from setupRun(). This could only be a problem if you never call that routine on restart.

**Comment by drhansj** [comment]
Ok - thanks, I will check.

How about for attenuation?

**Comment by andersp** [comment]
Let’s first get MR without attenuation going.

**Comment by drhansj** [comment]
Anders was able to find the problem(s) - the simulation wasn't setup correctly on restart! It needs 1 extra ghost point for mesh refinement, and one for ghost point values for viscoelastic attenuation.
