### ISSUE TITLE
test_sw4.py fails 1 test due to error tolerance?

### ISSUE THREAD

**Issue by drhansj** [geodynamics/sw4#45]
In running pytest/test_sw4.py on developer on MacOS, I get 1 / 16 tests failing:
```
INFO: compare_one_line: col= 0 test= 8.7590587e-06 base= 8.7588778e-06 err= 2.065333072693246e-05
ERROR: compare_one_line: err= 2.065333072693246e-05 > tolerance= 1e-05
Test # 5 Input file: refine-el-1.in FAILED
```
Would it be ok to increase the tolerance or is this a deeper problem?

**Comment by drhansj** [comment]
@andersp or @bjorn2 - I can fix if you approve the change

**Comment by andersp** [comment]
@drhansj Test #5 (refine-el-1.in) fails with (1 mpi task and 1-2-4 threads) on mac pro laptops (and perhaps other machines too). The test has been verified to pass with (1 thread, 4 mpi) and (2 threads, 2 mpi). The reason if passed on my machine is that the test script recognizes my machine and sets the number of mpi tasks to 4. For your machine, the script currently defaults to 1 mpi task. I have added another clause to the test script so all "Darwin" machines will use 4 mpi tasks.
