### ISSUE TITLE
Log output state number of CPU as 1 (although run on multiple cores?)

### ISSUE THREAD

**Issue by megies** [geodynamics/sw4#49]
I just compiled v2.0.1 on Debian 9 with onboard system libraries (libmpich12) and when I run the binary with `mpirun -np 2 sw4 ps-dir1.in`, the output says it runs on 1 CPU, although it properly runs on 2 CPUs, and all output seems to be doubled. Has somebody encountered this before and maybe has an idea how to fix it?

I know I had a v1.19 compiled at some point were it correctly showed no of CPU and did not multiply output all logging, but I can not find out anymore what MPI I used back then..

**Comment by andersp** [comment]
@megies, what you describe indicates that mpi is not properly installed on your system. Make sure you use consistent versions of the mpi compiler and execution script. On some machines, mpirun comes preinstalled and may not be compatible with, e.g., openmpi or mpich.

**Comment by megies** [comment]
Ah, yes, my bad, I've been picking up a wrong `mpirun` executable on my PATH. I was careful about PATH etc. when compiling but not careful enough when executing. Nevermind and thanks for the feedback!
