### ISSUE TITLE
volimage - VisIt plugin

### ISSUE THREAD

**Issue by mlabuta** [geodynamics/sw4#56]
Hello,
I would like to kindly ask, if it would be possible to add volimage plugin for VisIt into the GitHub repository. I tried to open volimage files in Visit as it's mentioned in the SW4 User guide but it seems to me, that the built-in VisIt plugin volimage is for opening files only from the older program WPP. As it looks like, the file extension has changed and as I suppose - also the file structure (header size etc...) and I am afraid I am not able to modify the C source code of the plugin in way that it would also load SW4 files.
So, if you could publish the modified volimage VisIt plugin (same as the sw4img plugin for viewing 2D images) I would be very grateful.
Kind regards,
Martin Labuta.

**Comment by andersp** [comment]
Did you try the visit plugin in the developer branch? The files are in tools/sw4img.

**Comment by mlabuta** [comment]
Thank you very much! I think it was problem on my side with incorrect installation of the plugin. After rebuilding visit it works nicely.
