### ISSUE TITLE
sw4-prof source code missing

### ISSUE THREAD

**Issue by houjun** [geodynamics/sw4#57]
The sw4-prof.h/C files are missing from @bjorn2 last commit, cannot compile sw4 without them.

**Comment by andersp** [comment]
I think Bjorn forgot to check those files in. He is having some computer issues at the moment but is aware of the problem.

**Comment by andersp** [comment]
The missing files have been added to the developer branch. Please update and try building again!

**Comment by houjun** [comment]
Working now.
